name = "marsalforn-home-web"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SITE_URL = "https://marsalforn-home-web.pages.dev"
ADMIN_OWNER_EMAILS = "seb.aquilina@gmail.com"

[[d1_databases]]
binding = "DB"
database_name = "marsalforn-home-db"
database_id = "488ee7cf-514f-44d9-8653-4e80814f665f"
migrations_dir = "drizzle/migrations"

[[kv_namespaces]]
binding = "DEAD_LETTER"
id = "70bbae63b12442429c541ec6f93c3b59"

[env.preview]
name = "marsalforn-home-web-preview"
[env.preview.vars]
NEXT_PUBLIC_SITE_URL = "https://preview.marsalforn-home-web.pages.dev"
ADMIN_OWNER_EMAILS = "seb.aquilina@gmail.com"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "marsalforn-home-preview"
database_id = "6662fa0d-c717-4ea5-afee-c5a5fe83c05b"
migrations_dir = "drizzle/migrations"

[[env.preview.kv_namespaces]]
binding = "DEAD_LETTER"
id = "70bbae63b12442429c541ec6f93c3b59"
